### ISSUE TITLE
Adding fields to logging within a block without using a child logger

### ISSUE THREAD

**Issue by jezstephens** [tilfin/ougai#107]
I am looking to achieve something similar to what is possible with [ActiveSupport::TaggedLogging](https://edgeapi.rubyonrails.org/classes/ActiveSupport/TaggedLogging.html):

```ruby
logger = ActiveSupport::TaggedLogging.new(Logger.new(STDOUT))
logger.tagged('BCX') { logger.info 'Stuff' }                            # Logs "[BCX] Stuff"
logger.tagged('BCX', "Jason") { logger.info 'Stuff' }                   # Logs "[BCX] [Jason] Stuff"
logger.tagged('BCX') { logger.tagged('Jason') { logger.info 'Stuff' } } # Logs "[BCX] [Jason] Stuff"
```

The important thing to note here is that the logger is mutated for the duration of the block execution - there is no "child logger" yielded to the block. This is useful because it is often difficult/impossible to inject the child logger into code called within the block. For example, many libraries only allow a logger to be provided once, on initialization.

A real-world use case would be to tag all logs produced while servicing a request with the request ID.

I could be missing something, but I don't see a nice way of doing this using Ougai. Is this something you would be interested in supporting?

So far, the best I have come up with is this:

```ruby
def with_log_fields(fields)
  previous_fields = logger.with_fields
  logger.with_fields = previous_fields.merge(fields)
  yield
ensure
  logger.with_fields = previous_fields
end

with_log_fields({request_id: request.id}) { logger.info("Something happened") }
```

I am hoping for something more like this to be supported out of the box:

```ruby
logger.with_fields({request_id: request.id}) { logger.info "Something happened" }
```

**Comment by tilfin** [comment]
@jezstephens Please use `before_log` with the thread-based store as the following code:
```ruby
require 'request_store'

class Rack::XRequestId
  def initialize(app)
    @app = app
  end

  def call(env)
    request = Rack::Request.new(env)
    RequestStore.store['HTTP_X_REQUEST_ID'] = request.get_header('X_REQUEST_ID')
    @app.call(env)
  end
end

class Application < Rails::Application
  config.middleware.use Rack::XRequestId
end

class Logger < Ougai::Logger
   include ActiveSupport::LoggerThreadSafeLevel
   include ActiveSupport::LoggerSilence

  def initialize(*args)
    super

    self.before_log = lambda do |data|
      request_id = RequestStore['HTTP_X_REQUEST_ID']
      data[:request_id] = request_id if request_id 
    end
  end
end
```

**Comment by jezstephens** [comment]
@tilfin, thanks very much for your help.

I'm not sure this is an ideal substitute for the suggested functionality in all cases, but it works well for my use case. It also seems like it would be possible to implement the `#with_fields {...}` functionality in a custom logger using a similar technique.

I will mark this issue as closed.

**Comment by letiesperon** [comment]
@tilfin Hi! I love the gem 
I haven't found any article on how to make the current user id get logged as a structured field in every log automatically without experiencing race conditions.
I ran into this answer. Would you still say using `RequestStore` is the right way to go?
In other words, having a `before_action` in my `ApplicationController` that sets the `current_user_id` in the `RequestStore`, and then modifying the `Logger` class to append it. Is that the recommended practice?

Thanks so much

**Comment by tilfin** [comment]
@letiesperon  I haven't touched Rails in years, so I can't judge if it's a best practice or not, but if you want to fill the logs with current user id, I think it will work that way as well.
