### ISSUE TITLE
Cannot load such file -- awesome_print when using logger.formatter = Ougai::Formatters::Readable.new

### ISSUE THREAD

**Issue by ovalenzuela19** [tilfin/ougai#108]
I run into the error of: Cannot load such file -- awesome_print when I use the Readable Formatter as specified in the wiki. 
Gemfile: `gem amazing_print`
Gemfile.lock: `amazing_print (1.2.1)`

**Comment by tilfin** [comment]
Tell me the ougai version you use. the latest version one shouldn't refer **awesome_print**.

**Comment by ovalenzuela19** [comment]
Using Ougai 1.8.2

**Comment by ovalenzuela19** [comment]
Using Ougai 1.8.2

**Comment by tilfin** [comment]
Please upgrade to 1.8.5

**Comment by ovalenzuela19** [comment]
Solved the issue! Thanks!
