### ISSUE TITLE
Getting issue for loading `Readable` object in production environment

### ISSUE THREAD

**Issue by sudeeptarlekar** [tilfin/ougai#109]
Right now we are using Ougai for logging in production, now as it is using `amazing_print` one the dependency we are facing issue while loading `Ougai::Formatters::Readable.new` in production

**Steps to reproduce**
1. Add. `Ougai` as gem in Gemfile
2. Run `bundle install` 
3. Start `rails console -e production`
4. `Ougai::Formatters::Readable.new`

**Actual Result**
```ruby
LoadError: cannot load such file -- amazing_print
from /Users/sudeepaniltarlekar/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
Caused by Bootsnap::LoadPathCache::FallbackScan:
```

**Expected Result**
```ruby
#<Ougai::Formatters::Readable:0x00007f8772dd1e30 ...>
```

**Possible Solution**
Right now `amazing_print` is under the `test` group in Gemfile, we should be moving that gem to the gemspec as a dependency

If this sounds good, will raise a PR

Thoughts?

**Comment by tilfin** [comment]
@sudeeptarlekar  I don't recommend the Readable formatter on the production environment. therefore if you want the Readable formatter, `gem 'amazing_print'` in the Gemfile of your application must be defined separately. There is the explanation on https://github.com/tilfin/ougai#use-human-readable-formatter-for-console .

**Comment by sudeeptarlekar** [comment]
Ahh my bad, I missed that, can we highlight that part or add a note in installation?

**Comment by sudeeptarlekar** [comment]
@tilfin if you think we should move that explanation or if we should add a link to that doc in top section, let me know I will create a PR or else feel free to close issue.

Thanks for your quick input, much appreciated.
