### ISSUE TITLE
Ougai::Logger#add not compatible with Rails

### ISSUE THREAD

**Issue by haines** [tilfin/ougai#114]
As suggested in the [wiki](https://github.com/tilfin/ougai/wiki/Use-as-Rails-logger), we're including `ActiveSupport::LoggerSilence` in our logger like so

```ruby
module OurRailsApp
  class Logger < Ougai::Logger
    include ActiveSupport::LoggerSilence
  end
end
```

However this is broken in 1.9.0 because of the changes in #113.

Including the `ActiveSupport::LoggerSilence` also includes `ActiveSupport::LoggerThreadSafeLevel`, which overrides `#add` and reverts it to the original signature ([here](https://github.com/rails/rails/blob/v6.1.1/activesupport/lib/active_support/logger_thread_safe_level.rb#L59)).

We then get an `ArgumentError` when we try to log anything:

```
ArgumentError: wrong number of arguments (given 4, expected 1..3)
gems/activesupport-6.1.1/lib/active_support/logger_thread_safe_level.rb:59:in `add'
gems/ougai-1.9.0/lib/ougai/logging.rb:42:in `debug'
```

**Comment by tilfin** [comment]
Thank you for your report.
Please continue to use v1.8 for now.

**Comment by tilfin** [comment]
released https://github.com/tilfin/ougai/releases/tag/v1.9.1

**Comment by haines** [comment]
v1.9.1 is working well, thanks for fixing this so quickly!
