### ISSUE TITLE
Logging ANSI colors

### ISSUE THREAD

**Issue by flah00** [tilfin/ougai#116]
I'm running into an issue, either with the colorize gem or with ougai...

When I set the ougai formatter to `Ougai::Formatters::Readable`, my colors turn dull. 

My setup is tmux (with a custom tmux 256 termcap), iterm, and solarized dark on a mac, if that helps. Also, I'm using colorize 0.8.1 and ougai 1.9.1 and ruby 2.6.6. 

## normal

```ruby
require 'colorize'
require 'ougai'
@logger = Ougai::Logger.new STDOUT
puts "red".red
puts "green".green
```

## dull

```ruby
require 'colorize'
require 'ougai'
@logger = Ougai::Logger.new STDOUT
@logger.formatter = Ougai::Formatters::Readable.new
puts "red".red
puts "green".green
```

**Comment by tilfin** [comment]
It seems like there is interference between the **colorize** and the **amazing_print** that the Readable formatter depends on.
https://github.com/amazing-print/amazing_print/blob/master/lib/amazing_print/core_ext/string.rb#L29

**Comment by tilfin** [comment]
Please try to use an alternative readable formatter or have one made by yourself.
https://github.com/tilfin/ougai/wiki/Awesom-Ougai#custom-formatters

**Comment by flah00** [comment]
Wow, that was quick! Thanks for pinning it down. I'll give it whirl.

**Comment by flah00** [comment]
For posterity:

```ruby
# frozen_string_literal: true
require 'ougai/formatters/readable'

class ReadableFormatter < Ougai::Formatters::Readable
  # override load_dependent, skip amazing_print, and colors render as expected
  def load_dependent
  end
end
```
