### ISSUE TITLE
Log redaction

### ISSUE THREAD

**Issue by Samuron** [tilfin/ougai#123]
Hello! Thank you for the awesome work you are doing.
Recently, I have encountered some issues when tried to do redaction. I have implemented it in following way:
```ruby
logger.before_log = lambda do |data|
  redact_sensitive(data)
end

def redact_sensitive(data)
  data.each do |key, value|
    if value.is_a?(Hash)
      redact_sensitive(value)
    elsif value.is_a?(String) && sensitive?(key)
      data[key] = "**REDACTED**"
    end
  end
end

def sensitive?(key)
 filter_parameters.include?(key.to_s)
end
```

This is working well but has one unfortunate sideeffect - it mutates the hash passed to log. Ougai does not take the defensive copy and if user will pass actual application data it can result in it being mutated. 

Maybe, I am using the wrong place to implement the logic or am missing something. Would really appreciate you pointing me in right direction.

**Comment by tilfin** [comment]
Exactly. Ougai does a shallow copy of the data, but not a deep copy.
https://github.com/tilfin/ougai/blob/main/lib/ougai/logger.rb#L133


So please duplicate all Hash values except the top level data by yourself.
I haven't tested the following code, but I think it will work as expected.

```rb
def redact_sensitive(data)
  data.each do |key, value|
    if value.is_a?(Hash)
      data[key] = nv = value.dup
      redact_sensitive(nv)
    elsif value.is_a?(String) && sensitive?(key)
      data[key] = "**REDACTED**"
    end
  end
end
```
