### ISSUE TITLE
Sub-logger support

### ISSUE THREAD

**Issue by eropple** [tilfin/ougai#23]
Hey there - Ougai looks _rad_ and I'm trying it out in a new project right now! Thanks for open-sourcing it.

One thing I noticed is that it doesn't support child loggers. It seems like you're familiar with `bunyan` for Node so I assume you know how they roll, but it really seems like something that might be nice to have (for example, I'm using it in a Grape API right now and I'd love my controllers to have their own logging tags)? If I get a chance I could take a crack at it, but either way I figured I'd drop a quick message to get the idea on your radar.

`#with_logger` is handy, but when you're going in and out of scopes, it's not quite so useful--I tend to think a new object probably makes some sense given how libraries often expect them.

**Comment by tilfin** [comment]
Hi, I have implemented **child logger** system. Is this feature matching your wish?
https://github.com/tilfin/ougai/blob/feature/child-logger/README.md#create-a-child-logger
If you are satisfied with it, I will release it.

**Comment by eropple** [comment]
Whoa, dude, that's awesome. That looks great.

**Comment by tilfin** [comment]
@eropple I released it on [ougai 1.2.0](https://rubygems.org/gems/ougai/versions/1.2.0).
If this is useful for you, please star this repo! thank you.

**Comment by eropple** [comment]
That's super cool--thanks for being so responsive.
