### ISSUE TITLE
Rendering time in UTC by default

### ISSUE THREAD

**Issue by eropple** [tilfin/ougai#56]
Might be a good idea to allow specification of the time zone Ougai should be using for its logs, at least as an arg for the JSON formatters. In production we run servers as UTC, but for obvious reasons my dev workstation doesn't. ;)

**Comment by tilfin** [comment]
The timezone is supposed to dependent on ENV['TZ'] in running OS 🤔

**Comment by tilfin** [comment]
I confirmed the following. My PC timezone is 'Asia/Tokyo' (+09:00).

```ruby
require 'rubygems'
require 'ougai'

logger = Ougai::Logger.new(STDOUT)
logger.info('Info message!')
```

```json
{"name":"bunyan","hostname":"mint3","pid":19327,"level":30,"time":"2018-02-21T17:19:05.712+09:00","v":0,"msg":"Info message!"}
```

**Comment by tilfin** [comment]
Please feel free to open this if there is something.
