### ISSUE TITLE
Consider Jruby compitability

### ISSUE THREAD

**Issue by skatkov** [tilfin/ougai#59]
Thanks for an interesting project!

It would be nice if this gem would play nicely with jruby. I've noticed a recent dependency change from 'json' gem to 'oj' gem. It's a good change to do if your on MRI, oj is significantly faster. But it doesn't have any support for Jruby
https://github.com/ohler55/oj/blob/fca1a69c15d4f17b0401416f6376553d517483f9/pages/Compatibility.md

Are you willing to consider https://github.com/intridea/multi_json gem as an alternative? This way you'll be able to use oj and jruby guys will have a chance to try out this gem as well.

**Comment by tilfin** [comment]
Thank you. I have revived JRuby support.   I consider to reduce dependency as possible, so I did not use multi_json.

**Comment by tilfin** [comment]
I released it on v1.6.6 .
