### ISSUE TITLE
call by tagged_logging so msg is String

### ISSUE THREAD

**Issue by stadia** [tilfin/ougai#71]
```
logger.rb:26:in `_call'
logger.rb:15:in `call'
gems/activesupport-5.1.6.1/lib/active_support/tagged_logging.rb:21:in `call'
ruby/2.5.0/logger.rb:584:in `format_message'
```
so print
```
{:msg=>"{:msg=> 'message'}"}
```

**Comment by tilfin** [comment]
@stadia Ougai does not support TaggedLogging because TaggedLogging forces logs to be string and inserts tags string to the head of logs.

**Comment by tilfin** [comment]
See https://github.com/tilfin/ougai/wiki/Use-as-Rails-logger#with-activesupporttaggedlogging
