### ISSUE TITLE
Ougai::Logger.broadcast will not work if formatter was used.

### ISSUE THREAD

**Issue by skatkov** [tilfin/ougai#75]
I have a very simple `LoggerBuilder` class, main requirement for it is to:
- Output `readable` version of logs into STDOUT
- Output regular version to file

here is a code.
```
require 'ougai'

class LoggerBuilder
  attr_reader :logger

  def self.build(component_name)
    builder = new(component_name)
    builder.logger
  end

  def initialize(to_file)
    file_logger = Ougai::Logger.new(File.open("logs/#{to_file}.log", "a"))
    @logger = Ougai::Logger.new(STDOUT)
    @logger.formatter = Ougai::Formatters::Readable.new
    @logger.extend Ougai::Logger.broadcast(file_logger)
  end
end
```

in this scenario, logs will not be written to file. BUT if I'll comment out like with formatter

```
   #@logger.formatter = Ougai::Formatters::Readable.new
```

it works!

So, I'm not sure if this is a feature or a `bug`. But I decided to report to see what you think.

**Comment by skatkov** [comment]
I tried to rewrite those loggers slightly differently.  But this version didn't work for me either.

```
    stdout_logger = Ougai::Logger.new(STDOUT)
    stdout_logger.formatter = Ougai::Formatters::Readable.new
    @logger = Ougai::Logger.new(File.open("logs/#{to_file}.log", "a"))
    @logger.extend Ougai::Logger.broadcast(stdout_logger)
```

**Comment by tilfin** [comment]
@skatkov Tell me your using ougai gem version and platform. I tried to the above code but it worked without problems 🤔

**Comment by skatkov** [comment]
@tilfin sorry, forgot to add it.
```
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]
macOS 10.14.3
```

**Comment by tilfin** [comment]
@skatkov My environment is the same as yours. Tell me about the problem in detail.

**Comment by skatkov** [comment]
I've noticed that you have some specs for #broadcast method. Once I'll be at a computer, I'll try to reproduce issue through specs and create a pull request.

**Comment by skatkov** [comment]
So I was unable to reproduce this error in rspec tests, but I've managed to this it in my application.

I'm using `foreman` tool to launch two processes -- producer.rb and consumer.rb

#Procfile
```
domain_producer: bundle exec ruby app/producer.rb
domain_consumer: bundle exec ruby app/consumer.rb
```

example of `producer.rb`
```
# frozen_string_literal: true

logger = LoggerBuilder.build do |logger|
  logger.to_file('producer')
end

```

both of them use `LoggerBuilder`, but both of them write to separate files.

Here is LoggerBuilder:
```
# frozen_string_literal: true

require 'ougai'

class LoggerBuilder
  attr_reader :logger

  def self.build
    builder = new
    yield(builder) if block_given?
    builder.logger
  end

  def initialize
    @logger = Ougai::Logger.new(STDOUT)
    @logger.formatter = Ougai::Formatters::Readable.new
  end

  def to_file(name)
    file_logger = Ougai::Logger.new(File.open("logs/#{name}.log", "a"))
    @logger.extend Ougai::Logger.broadcast(file_logger)
  end
end
```


So if I drop magic comment `# frozen_string_literal: true` from producer.rb and consumer.rb, then logs are being written to files. But with frozen_strings -- files are empty, nothing get's written.

**Comment by tilfin** [comment]
@skatkov How about trying `Ougai::Logger.new("logs/#{name}.log")` ? I don't understand why frozen_string_literal affects output. But the log file sync modes are different by ruby logger than by yours.
https://github.com/ruby/ruby/blob/trunk/lib/logger.rb#L737
