### ISSUE TITLE
`logger.info(progname) { message }` syntax not supported

### ISSUE THREAD

**Issue by jbodah** [tilfin/ougai#78]
The default `Logger` can accepts a progname with block syntax e.g. the following will set `progname` to `initialize` which is forwarded to the `Logger::Formatter`'s `call` method:

```rb
logger.info('initialize') { "Initializing..." }
```

This does not seem to be supported by Ougai from what I can tell

**Comment by tilfin** [comment]
Yes, Ougai does currently not support `progname`. I think that it is better to use `logger.child()` with one field than specifying `progname` for each log. For future reference, I would like to know how you use `progname`.

**Comment by jbodah** [comment]
Ah, I had some old code that was constructing the source of calls (e.g. `Klass.method`) that fit naturally into progname for Logger and I was just surprised to run into an issue when I upgraded it to Ougai
