### ISSUE TITLE
Change log level from number to log name

### ISSUE THREAD

**Issue by PoombavaiS** [tilfin/ougai#83]
When I try to print the below log, it prints "level" in numbers. Instead, I want it in the log level name itself.
`logger.info('Information!')
{"name":"main","hostname":"mint","pid":14607,"level":30,"time":"2016-10-16T22:26:48.835+09:00","v":0,"msg":"Information!"}`

Am expecting,

`logger.info('Information!')
{"name":"main","hostname":"mint","pid":14607,"level":"Info","time":"2016-10-16T22:26:48.835+09:00","v":0,"msg":"Information!"}`
 How to do this?

**Comment by tilfin** [comment]
Please make suitable formatter for your project referring to https://github.com/tilfin/ougai/blob/master/lib/ougai/formatters/bunyan.rb.

For example,
```ruby
require 'rubygems'
require 'ougai'

class YourFormatter < Ougai::Formatters::Base
  include Ougai::Formatters::ForJson

  def initialize(app_name = nil, hostname = nil, opts = {})
    aname, hname, opts = Ougai::Formatters::Base.parse_new_params([app_name, hostname, opts])
    super(aname, hname, opts)
    init_opts_for_json(opts)
  end

  def _call(severity, time, progname, data)
    dump({
      name: progname || @app_name,
      hostname: @hostname,
      pid: $$,
      level: severity.downcase,
      time: time,
      v: 0
    }.merge(data))
  end

  def convert_time(data)
    data[:time] = format_datetime(data[:time])
  end
end

logger = Ougai::Logger.new(STDOUT)
logger.formatter = YourFormatter.new
logger.info('a message', foo: 100)
```

```
{"name":"yours","hostname":"mint3","pid":25620,"level":"info","time":"2019-07-30T18:15:12.972+09:00","v":0,"msg":"a message","foo":100}
```

**Comment by zw963** [comment]
i am wired too why we use number instead level name, thank you.

**Comment by tilfin** [comment]
If the log level is numeric, the log service can filter the logs easily like `{$ .level> 30 }` .

**Comment by zw963** [comment]
> If the log level is numeric, the log service can filter the logs easily like `{ $.level> 30 }`

Can we use  `{ $.level> 30 }` filter in kibana? it is not worked for me.

![image](https://user-images.githubusercontent.com/549126/62831041-8a472c00-bc4b-11e9-8ea6-8bfaf63d9b37.png)

But filter by string is more rememberable.

**Comment by zw963** [comment]
thank you,  kibanba can use: 'level > 30' directly.
