### ISSUE TITLE
Keep rails old format log output to file when use ougai logger.

### ISSUE THREAD

**Issue by zw963** [tilfin/ougai#84]
As lograge does:

```rb
Rails.application.configure do
  config.lograge.keep_original_rails_log = true

  config.lograge.logger = ActiveSupport::Logger.new "#{Rails.root}/log/lograge_#{Rails.env}.log"
end
```

**Comment by tilfin** [comment]
Ougai is main logger system, not specialized for one feature like a Lograge for request. therefore the logs that Ougai outputs is original.
How do you actually want to output logs?

**Comment by zw963** [comment]
Sorry for confuse, what i means, when config to use ougai, how to keep `rails old  format logger`
still output to some file, e.g.  `log/production.log`.

when i set config.logger to use ougai logger,  production.log could not see any output.

**Comment by tilfin** [comment]
It is impossible because ActiveSupport::Logger can not parse the structure logging that Ougai::Logger outputs. I recommend you to use Readable formatter on development and to use bunyan or pino CLI to format JSON logs on production, for looking logs easily.

**Comment by zw963** [comment]
Is there any change to output old rails log to file before process to json?

For clarify my question, following is my config, most of my code is come from WiKi, with some change.

https://github.com/zw963/test_fluentd/blob/v0.1/lib/fluent_logger.rb

When i set `config.logger = AppLogger.logger` in `production.rb`,  it worked well.
but, i have no idea about how to output logger to log/production.log.

**Comment by tilfin** [comment]
The broadcast feature can output to both fluentd and production.log. https://github.com/tilfin/ougai#using-broadcast-log-output-plural-targets

**Comment by zw963** [comment]
Thank you for reply, code like following is not work, because i have no idea to get the 
Rails Tagged request id (one UUID), like this: [08caa364-3792-414d-be4d-f8691f7e4d65],
when it output `log/production.log`,  `ActiveSupport::TaggedLoggingJSON` hack (for add "tags":  [08caa364-3792-414d-be4d-f8691f7e4d65]) is not work, it value always [].

```rb
logger = ActiveSupport::Logger.new('log/production.log')
      logger.formatter = ::Logger::Formatter.new
      self.logger = ActiveSupport::TaggedLogging.new(logger)

      json_logger = Base.new(FluentLoggerDevice.new('some_ip', 24224))
      json_logger.with_fields = { tag: 'app.worker', tags: self.logger.formatter.current_tags }
      json_logger = ActiveSupport::TaggedLoggingJSON.new(json_logger)

      logger.extend Ougai::Logger.broadcast(json_logger)
```

BTW:

 [This](https://github.com/tilfin/ougai#using-broadcast-log-output-plural-targets) example is seem to not work, when i test,  `STDOUT` and `error.log` all output same log with all three lines, maybe need fix.

```
# Logfile created on 2019-08-12 19:42:01 +0800 by logger.rb/66358
{"name":"1","hostname":"lggram","pid":24567,"level":30,"time":"2019-08-12T19:42:01.381+08:00","v":0,"msg":"Hello!"}
{"name":"1","hostname":"lggram","pid":24567,"level":50,"time":"2019-08-12T19:42:01.382+08:00","v":0,"msg":"Failed to do something."}
{"name":"1","hostname":"lggram","pid":24567,"level":40,"time":"2019-08-12T19:42:01.382+08:00","v":0,"msg":"Ignored something."}
```

**Comment by zw963** [comment]
Don't know why, when use `Ougai::Logger.broadcast`, will cause logger missing.

Following is Ougai broadcast output:

![image](https://user-images.githubusercontent.com/549126/62915149-ef269180-bdc5-11e9-9e08-7801539b048a.png)

if use ActiveSupport::Logger.broadcast, output this:

![image](https://user-images.githubusercontent.com/549126/62915182-06657f00-bdc6-11e9-8970-7afa07ed2f22.png)

**Comment by tilfin** [comment]
Thank you @zw963, telling me about wrong README.

The broadcast feature supports only Ougai logging, not ActiveSupport logging. 
There is no way that both sending structure logs to fluentd and writing original rails logs to a file are satisfied.

**Comment by tilfin** [comment]
I found that `Ougai::Logger.broadcast` currently has the bug if logging method is called with block, so I fix it by #92.

**Comment by zw963** [comment]
Don't know if this behavior is expect, what i want is:

1. output original format log to  'production.log'
2.  output jsonfied logger to fluentd.

so , i have following code. (as same above)

![image](https://user-images.githubusercontent.com/549126/63958373-cf2ce880-cabc-11e9-92d4-0b03bcaa97c6.png)

When use master branch code, i see no log write to fluent,  i don't know if this is 
expected fixed behavior.

**Comment by tilfin** [comment]
> The broadcast feature supports only Ougai logging, not ActiveSupport logging.

It is the answer.

**Comment by zw963** [comment]
Thank you.
