### ISSUE TITLE
Child logger - level

### ISSUE THREAD

**Issue by kleinron** [tilfin/ougai#85]
AFAIU, child logger can only add fields to its parent logger, according to some logic.
However, when it comes to the child logger's level, it is purely inherited from the parent logger.
Is there a way to set the child logger's level, too?
If not, maybe there is a way to clone a logger and set a different log level to the cloned object?

**Comment by tilfin** [comment]
Yes, a child logger is inherited from the log level of its parent. There is no way to solve it currently.
Why do you want to change the level of child loggers?

**Comment by kleinron** [comment]
I'm using an external gem, and I want to pass it a child logger with additional fields.
For instance, I'm using _Sneakers_, and I'd like _Sneakers_ to use the same logger (with all of its settings).
However, I'm only interested in logging Sneakers errors. Other entries (of level warn, info and debug) are irrelevant for my application, and make white noise.
For this reason I want to have some kind of a clone to the "main" logger.
I thought that a child logger is the way to go, but I can't control its log level.
I therefore ask if there's a way to clone a logger so that the level of the cloned object could be changed.

**Comment by tilfin** [comment]
I understood.

The child logger feature applies somethings to a log recursively. Suppose a child logger can have the log level, it is not clear which level is actually outputted if the main logger is error level and the child's is info level.

But, I also understood the use case. I will implement a feature to solve it.

**Comment by tilfin** [comment]
I will implement level setter on child logger simply after I confirmed https://github.com/jondot/sneakers/blob/b4f44aac5c06ea0448427d8ee351a86f9db4a478/lib/sneakers.rb#L50 .

**Comment by tilfin** [comment]
released v1.8.0
