### ISSUE TITLE
Invalid JSON generated when logging stack traces, which happens in Rails and ActiveJob 

### ISSUE THREAD

**Issue by jensljungblad** [tilfin/ougai#94]
Trying to use ougai together with Rails. Ran into a problem with one of the default Rails logs from ActiveJob. When a job fails it logs something like "Error performing job" followed by a stack trace. This trace contains `\n` characters. This results in an ougai line such as:

```
{"name":"main", "msg":"Error performing job \n ..."}
```

Which is invalid JSON. Is ougai not guaranteed to output valid JSON?

**Comment by jensljungblad** [comment]
Never mind! User error :)

**Comment by bestwebua** [comment]
I have the same issue. One application. During local running everything is okay. But when I run it on the demo env I see broken log structure:

```
{"name":"rackup","hostname":"4a37fsdf352a47","pid":9,"level":30,"time":"2023-09-22T14:26:36.298+00:00","v":0,"msg":"{:msg=>\"No message\", :service_name=>\"my-service\", :service_version=>\"1.0.0\", :team=>\"my-team\", :trace_id=>\"d0e7a1f58c8ffbb50a2655b465e76e77\", :span_id=>\"f05a320ca0b6aa96\"}"}
```

Under `msg` key we can see collected not serialized as json context, that should be in the root of expected json. Any ideas?
