### ISSUE TITLE
JSON logger severity fields not conforming to syslog standards

### ISSUE THREAD

**Issue by brafales** [tilfin/ougai#95]
Hi,

We've noticed the JSON logger doesn't conform to the standard syslog severity values:
- Here's ougai implementation: https://github.com/tilfin/ougai/blob/d3f1412668e302a904fbf8271954c260c0bf472a/lib/ougai/formatters/for_json.rb#L18
- Here are the standard levels for the different severity values according to syslog: https://en.wikipedia.org/wiki/Syslog#Severity_level which happen to be the same ones as Ruby `Logger` class uses.

Is that intentional? And if so what is the reasoning behind it? Would you consider changing these values to be the standard syslog values?

Thanks

**Comment by tilfin** [comment]
Yes, because those severity values are used by both https://github.com/trentm/node-bunyan and https://github.com/pinojs/pino for JavaScript.

If you would like to apply the syslog severity values, please override to_level method on your formatter.
