### ISSUE TITLE
Will ougai support #silence method? (Rails::RackLogger#silence)

### ISSUE THREAD

**Issue by tomlla** [tilfin/ougai#96]
# Background

My application code and libraries code call `#silence` method for logger instance.

For example, Sprockets calls it

sprockets-rails-3.2.1/lib/sprockets/rails/quiet_assets.rb

```rb
module Sprockets
  module Rails
    class QuietAssets
      def initialize(app)
        @app = app
        @assets_regex = %r(\A/{0,2}#{::Rails.application.config.assets.prefix})
      end

      def call(env)
        if env['PATH_INFO'] =~ @assets_regex
          ::Rails.logger.silence { @app.call(env) }
        else
          @app.call(env)
        end
      end
    end
  end
end
```

# Problem

Ougai doesn't have #silence method. so exception raised when #silence is called.
(of course the exception is not json... )

# Question

1. @tilfin Do you have a plan about `#silence` method implementation?(extend?)
2. Is there have an idea about fixing the exception in application code

Links
- https://github.com/rails/rails/blob/master/activesupport/lib/active_support/logger_silence.rb

**Comment by tomlla** [comment]
my configuration is like this

config/environments/xxx.rb
```rb
  require 'ougai'
  config.logger = Ougai::Logger.new(STDOUT)
```

**Comment by tomlla** [comment]
Sorry I didn't read these docs... I'll read them

- https://github.com/tilfin/ougai/wiki/Use-as-Rails-logger
- https://github.com/tilfin/ougai/wiki/Use-as-Rack-logger

**Comment by tilfin** [comment]
@tomlla Have you already implemented your app logger like the example on https://github.com/tilfin/ougai/wiki/Use-as-Rails-logger ?

**Comment by tomlla** [comment]
Not yet. but I'm finding a method to logging requestId before logger implementation.

↓ I used uuid request-id in rails default logger
```
  config.log_tags = [:uuid]
```

Do you have something points to be careful of logger implementation?

**Comment by tilfin** [comment]
@tomlla try to patch https://github.com/tilfin/ougai/wiki/Use-as-Rails-logger#with-activesupporttaggedlogging

**Comment by tomlla** [comment]
@tilfin Thank you I'll try it :smiley:
