### ISSUE TITLE
Loglevel not working

### ISSUE THREAD

**Issue by MicMicMon** [tilfin/ougai#97]
I have the following config for my tests:
```ruby
config.lograge.enabled = true
console_logger = Ougai::Logger.new(STDOUT)
console_logger.level = Logger::ERROR

# Assign Ougai logger
config.logger = console_logger
```

And my output still has warn & info outputs such as:

```json
{"name":"rspec","hostname":"localhost.localdomain","pid":42514,"level":30,"time":"2019-12-14T12:48:36.574+01:00","v":0,"msg":"Added roles 'executive' to user xxxx"}
```

Where I can see that the `level` field seems ok.

What am I missing?

**Comment by tilfin** [comment]
Is this file `config/environments/test.rb` ? If it is true, the log level is set again after the code.

**Comment by MicMicMon** [comment]
Yes it is.
Can't see any other place where it would be set, greping on ".level" gives nothing else.
Do you think of a place to look for?

**Comment by tilfin** [comment]
@MicMicMon Try to the following code
```
config.log_level = Logger::ERROR
config.logger = console_logger
```
FYI) https://github.com/rails/rails/blob/ee10e05af27facf42b1c49f8aaa0463d3af6989c/railties/lib/rails/application/bootstrap.rb#L53

**Comment by MicMicMon** [comment]
Weird, doing so makes the tests fail with :

```
An error occurred while loading rails_helper.
Failure/Error: require File.expand_path('../config/environment', __dir__)

NameError:
  wrong constant name 3
# ./config/environment.rb:5:in `<top (required)>'
# ./spec/rails_helper.rb:6:in `require'
# ./spec/rails_helper.rb:6:in `<top (required)>'
No examples found.
No examples found.


Finished in 0.00003 seconds (files took 0.62851 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples

Finished in 0.00003 seconds (files took 0.62851 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples
```

**Comment by MicMicMon** [comment]
Ah ok, got it to work with:

```ruby
config.log_level = 'ERROR'
```
The `const_get` was failing in your example, expecting a string/symbol actually.

So, right, it works!
Is it expected, should it be documented?

**Comment by tilfin** [comment]
It's not limited to Ougai, just about Rails configuration.

**Comment by MicMicMon** [comment]
Ah ok.

Thanks for your help!

Might be worth mentioning in the doc though, it's confusing for someone who doesn't know the internals like me, you don't suspect something else overwrites the config :)
